### ISSUE TITLE
Implement `WriteString` and `ReadString` methods

### ISSUE THREAD

**Issue by utkarshdagoat** [IMGIITRoorkee/Memoria#23]
Currently the `Write` and `Read` methods works with  `[]byte` make string version of the same. 

Just make wrapper functions around the methods that takes in string and convert that string to bytes and pass it to the corresponding function. Here is how you convert `strings` to  corresponding`[]byte` :
```golang
val := []byte(s) // here s is the string and val is the correspoding []byte value to pass to the function
```

**Comment by Ritchie6** [comment]
**_Implement WriteString and ReadString methods Issue #23_**
Following are the changes made in the code:

<img width="1280" alt="Screenshot 2024-12-18 at 12 18 36 PM" src="https://github.com/user-attachments/assets/5a14e607-40fe-4226-a045-9035ea9044e7" />
